/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.wmstudio.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing26thjuly_.wmstudio.CallRouting;

/**
 * Service object for domain model class CallRouting.
 *
 * @see {@link CallRouting}
 */
public interface CallRoutingService {

    /**
     * Creates a new CallRouting.
     *
     * @param callRouting The information of the created CompositeTable.
     * @return The created CallRouting.
     */
	CallRouting create(CallRouting callRouting);


	/**
	 * Finds CallRouting by id.
	 *
	 * @param callRoutingId The id of the wanted CallRouting.
	 * @return The found CallRouting. If no CallRouting is found, this method returns null.
	 */
	CallRouting getById(Double callRoutingId) throws EntityNotFoundException;

	/**
	 * Updates the information of a CallRouting.
	 *
	 * @param callRouting The information of the updated CallRouting.
	 * @return The updated CallRouting.
     *
	 * @throws EntityNotFoundException if no CallRouting is found with given id.
	 */
	CallRouting update(CallRouting callRouting) throws EntityNotFoundException;

    /**
	 * Deletes a CallRouting.
	 *
	 * @param callRoutingId The id of the deleted CallRouting.
	 * @return The deleted CallRouting.
     *
	 * @throws EntityNotFoundException if no CallRouting is found with the given id.
	 */
	CallRouting delete(Double callRoutingId) throws EntityNotFoundException;

	/**
	 * Finds all CallRoutings.
	 *
	 * @return A list of CallRoutings.
	 */
    @Deprecated
	Page<CallRouting> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all CallRoutings.
	 * @return A list of CallRoutings.
	 */
    Page<CallRouting> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the CallRoutings in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the CallRouting.
	 */
	long count(String query);

    Page<CallRouting> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

