/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.testingdb123.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing26thjuly_.testingdb123.Table77;

/**
 * Service object for domain model class Table77.
 *
 * @see {@link Table77}
 */
public interface Table77Service {

    /**
     * Creates a new Table77.
     *
     * @param table77 The information of the created CompositeTable.
     * @return The created Table77.
     */
	Table77 create(Table77 table77);


	/**
	 * Finds Table77 by id.
	 *
	 * @param table77Id The id of the wanted Table77.
	 * @return The found Table77. If no Table77 is found, this method returns null.
	 */
	Table77 getById(Long table77Id) throws EntityNotFoundException;

	/**
	 * Updates the information of a Table77.
	 *
	 * @param table77 The information of the updated Table77.
	 * @return The updated Table77.
     *
	 * @throws EntityNotFoundException if no Table77 is found with given id.
	 */
	Table77 update(Table77 table77) throws EntityNotFoundException;

    /**
	 * Deletes a Table77.
	 *
	 * @param table77Id The id of the deleted Table77.
	 * @return The deleted Table77.
     *
	 * @throws EntityNotFoundException if no Table77 is found with the given id.
	 */
	Table77 delete(Long table77Id) throws EntityNotFoundException;

	/**
	 * Finds all Table77s.
	 *
	 * @return A list of Table77s.
	 */
    @Deprecated
	Page<Table77> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all Table77s.
	 * @return A list of Table77s.
	 */
    Page<Table77> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table77s in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the Table77.
	 */
	long count(String query);

    Page<Table77> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

