/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing26thjuly_.demo.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.testing26thjuly_.demo.Table10;
import com.testing26thjuly_.demo.service.Table10Service;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

/**
 * Controller object for domain model class Table10.
 * @see Table10
 */
@RestController("Demo.Table10Controller")
@RequestMapping("/Demo/Table10")
@Api(description = "Exposes APIs to work with Table10 resource.", value = "Table10Controller")
public class Table10Controller {

    private static final Logger LOGGER = LoggerFactory.getLogger(Table10Controller.class);

    @Autowired
    @Qualifier("Demo.Table10Service")
    private Table10Service table10Service;

    /**
     * @deprecated Use {@link #findTable10s(String)} instead.
     */
    @Deprecated
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of Table10 instances matching the search criteria.")
    public Page<Table10> findTable10s(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Table10s list");
        return table10Service.findAll(queryFilters, pageable);
    }

    @RequestMapping(method = RequestMethod.GET)
    @ApiOperation(value = "Returns the list of Table10 instances matching the search criteria.")
    public Page<Table10> findTable10s(@RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Table10s list");
        return table10Service.findAll(query, pageable);
    }

    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @ApiOperation(value = "Returns downloadable file for the data.")
    public Downloadable exportTable10s(@PathVariable("exportType") ExportType exportType, @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        return table10Service.export(exportType, query, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service Table10Service instance
	 */
    protected void setTable10Service(Table10Service service) {
        this.table10Service = service;
    }

    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Creates a new Table10 instance.")
    public Table10 createTable10(@RequestBody Table10 table10) {
        LOGGER.debug("Create Table10 with information: {}", table10);
        table10 = table10Service.create(table10);
        LOGGER.debug("Created Table10 with information: {}", table10);
        return table10;
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the total count of Table10 instances.")
    public Long countTable10s(@RequestParam(value = "q", required = false) String query) {
        LOGGER.debug("counting Table10s");
        return table10Service.count(query);
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the Table10 instance associated with the given id.")
    public Table10 getTable10(@PathVariable(value = "id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting Table10 with id: {}", id);
        Table10 foundTable10 = table10Service.getById(id);
        LOGGER.debug("Table10 details with id: {}", foundTable10);
        return foundTable10;
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Updates the Table10 instance associated with the given id.")
    public Table10 editTable10(@PathVariable(value = "id") Integer id, @RequestBody Table10 table10) throws EntityNotFoundException {
        LOGGER.debug("Editing Table10 with id: {}", table10.getId());
        table10.setId(id);
        table10 = table10Service.update(table10);
        LOGGER.debug("Table10 details with id: {}", table10);
        return table10;
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Deletes the Table10 instance associated with the given id.")
    public boolean deleteTable10(@PathVariable(value = "id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Table10 with id: {}", id);
        Table10 deletedTable10 = table10Service.delete(id);
        return deletedTable10 != null;
    }
}
