/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FormLayout generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`FormLayout`", schema = "dbo")
public class FormLayout implements Serializable {

    private int id;
    private Integer intCol1;
    private Integer intCol2;
    private Integer intCol3;
    private Integer intCol4;
    private Integer intCol5;
    private Integer intCol6;
    private Integer intCol7;
    private Integer intCol8;
    private Short shortCol9;
    private Byte byteCol10;
    private String stringCol1;
    private String stringCol2;
    private String textCol3;
    private String stringCol3;
    private String textCol4;
    private Boolean booleanCol;
    private Character charCol4;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "`Int Col1`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol1() {
        return this.intCol1;
    }

    public void setIntCol1(Integer intCol1) {
        this.intCol1 = intCol1;
    }

    @Column(name = "`Int Col2`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol2() {
        return this.intCol2;
    }

    public void setIntCol2(Integer intCol2) {
        this.intCol2 = intCol2;
    }

    @Column(name = "`Int Col3`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol3() {
        return this.intCol3;
    }

    public void setIntCol3(Integer intCol3) {
        this.intCol3 = intCol3;
    }

    @Column(name = "`Int Col4`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol4() {
        return this.intCol4;
    }

    public void setIntCol4(Integer intCol4) {
        this.intCol4 = intCol4;
    }

    @Column(name = "`Int Col5`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol5() {
        return this.intCol5;
    }

    public void setIntCol5(Integer intCol5) {
        this.intCol5 = intCol5;
    }

    @Column(name = "`Int Col6`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol6() {
        return this.intCol6;
    }

    public void setIntCol6(Integer intCol6) {
        this.intCol6 = intCol6;
    }

    @Column(name = "`Int Col7`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol7() {
        return this.intCol7;
    }

    public void setIntCol7(Integer intCol7) {
        this.intCol7 = intCol7;
    }

    @Column(name = "`Int Col8`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol8() {
        return this.intCol8;
    }

    public void setIntCol8(Integer intCol8) {
        this.intCol8 = intCol8;
    }

    @Column(name = "`Short Col9`", nullable = true, scale = 0, precision = 5)
    public Short getShortCol9() {
        return this.shortCol9;
    }

    public void setShortCol9(Short shortCol9) {
        this.shortCol9 = shortCol9;
    }

    @Column(name = "`Byte Col10`", nullable = true, scale = 0, precision = 2)
    public Byte getByteCol10() {
        return this.byteCol10;
    }

    public void setByteCol10(Byte byteCol10) {
        this.byteCol10 = byteCol10;
    }

    @Column(name = "`String Col1`", nullable = true, length = 255)
    public String getStringCol1() {
        return this.stringCol1;
    }

    public void setStringCol1(String stringCol1) {
        this.stringCol1 = stringCol1;
    }

    @Column(name = "`String Col2`", nullable = true, length = 255)
    public String getStringCol2() {
        return this.stringCol2;
    }

    public void setStringCol2(String stringCol2) {
        this.stringCol2 = stringCol2;
    }

    @Column(name = "`Text Col3`", nullable = true, length = 255)
    public String getTextCol3() {
        return this.textCol3;
    }

    public void setTextCol3(String textCol3) {
        this.textCol3 = textCol3;
    }

    @Column(name = "`String Col3`", nullable = true, length = 255)
    public String getStringCol3() {
        return this.stringCol3;
    }

    public void setStringCol3(String stringCol3) {
        this.stringCol3 = stringCol3;
    }

    @Column(name = "`Text Col4`", nullable = true, length = 255)
    public String getTextCol4() {
        return this.textCol4;
    }

    public void setTextCol4(String textCol4) {
        this.textCol4 = textCol4;
    }

    @Column(name = "`Boolean Col`", nullable = true)
    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    @Column(name = "`Char Col4`", nullable = true, length = 1)
    public Character getCharCol4() {
        return this.charCol4;
    }

    public void setCharCol4(Character charCol4) {
        this.charCol4 = charCol4;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FormLayout)) return false;
        final FormLayout formLayout = (FormLayout) o;
        return Objects.equals(getId(), formLayout.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

