/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * UtableComposites generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`UTABLE_COMPOSITES`", schema = "dbo")
@IdClass(UtableCompositesId.class)
public class UtableComposites implements Serializable {

    private String id;
    private String companyId;
    private String contactName;
    private String address;
    private String city;

    @Id
    @Column(name = "`ID`", nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Id
    @Column(name = "`CompanyID`", nullable = false, length = 36)
    public String getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    @Column(name = "`ContactName`", nullable = false, length = 60)
    public String getContactName() {
        return this.contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    @Column(name = "`Address`", nullable = false, length = 30)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "`City`", nullable = false, length = 30)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UtableComposites)) return false;
        final UtableComposites utableComposites = (UtableComposites) o;
        return Objects.equals(getId(), utableComposites.getId()) &&
                Objects.equals(getCompanyId(), utableComposites.getCompanyId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getCompanyId());
    }
}

