/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * ViewUtable2 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`View_Utable2`", schema = "dbo")
@IdClass(ViewUtable2Id.class)
public class ViewUtable2 implements Serializable {

    private String id;
    private String company;
    private String contactName;
    private String address;
    private String city;

    @Id
    @Column(name = "`ID`", nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Id
    @Column(name = "`Company`", nullable = false, length = 30)
    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    @Id
    @Column(name = "`ContactName`", nullable = false, length = 60)
    public String getContactName() {
        return this.contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    @Id
    @Column(name = "`Address`", nullable = false, length = 30)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Id
    @Column(name = "`City`", nullable = false, length = 30)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ViewUtable2)) return false;
        final ViewUtable2 viewUtable2 = (ViewUtable2) o;
        return Objects.equals(getId(), viewUtable2.getId()) &&
                Objects.equals(getCompany(), viewUtable2.getCompany()) &&
                Objects.equals(getContactName(), viewUtable2.getContactName()) &&
                Objects.equals(getAddress(), viewUtable2.getAddress()) &&
                Objects.equals(getCity(), viewUtable2.getCity());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getCompany(),
                getContactName(),
                getAddress(),
                getCity());
    }
}

