/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ViewSelfRelation generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`View_SelfRelation`", schema = "dbo")
@IdClass(ViewSelfRelationId.class)
public class ViewSelfRelation implements Serializable {

    private int id;
    private Date dateCol;
    private Date datetimeCol;
    private Date timeCol;
    private Date timestampCol;
    private Boolean booleanCol;
    @JsonIgnore
    private byte[] blobCol;
    private Integer intCol;

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Id
    @Temporal(TemporalType.DATE)
    @Column(name = "`Date Col`", nullable = true)
    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "`Datetime Col`", nullable = true)
    public Date getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(Date datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    @Id
    @Temporal(TemporalType.TIME)
    @Column(name = "`Time Col`", nullable = true)
    public Date getTimeCol() {
        return this.timeCol;
    }

    public void setTimeCol(Date timeCol) {
        this.timeCol = timeCol;
    }

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "`Timestamp Col`", nullable = true)
    public Date getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Date timestampCol) {
        this.timestampCol = timestampCol;
    }

    @Id
    @Column(name = "`Boolean Col`", nullable = true)
    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    @Id
    @Column(name = "`Blob Col`", nullable = true)
    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    @Id
    @Column(name = "`Int Col`", nullable = true, scale = 0, precision = 10)
    public Integer getIntCol() {
        return this.intCol;
    }

    public void setIntCol(Integer intCol) {
        this.intCol = intCol;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ViewSelfRelation)) return false;
        final ViewSelfRelation viewSelfRelation = (ViewSelfRelation) o;
        return Objects.equals(getId(), viewSelfRelation.getId()) &&
                Objects.equals(getDateCol(), viewSelfRelation.getDateCol()) &&
                Objects.equals(getDatetimeCol(), viewSelfRelation.getDatetimeCol()) &&
                Objects.equals(getTimeCol(), viewSelfRelation.getTimeCol()) &&
                Objects.equals(getTimestampCol(), viewSelfRelation.getTimestampCol()) &&
                Objects.equals(getBooleanCol(), viewSelfRelation.getBooleanCol()) &&
                Objects.equals(getBlobCol(), viewSelfRelation.getBlobCol()) &&
                Objects.equals(getIntCol(), viewSelfRelation.getIntCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getDateCol(),
                getDatetimeCol(),
                getTimeCol(),
                getTimestampCol(),
                getBooleanCol(),
                getBlobCol(),
                getIntCol());
    }
}

