/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing26thjuly_.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.testing26thjuly_.wmstudio.Table2;
import com.testing26thjuly_.wmstudio.service.Table2Service;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

/**
 * Controller object for domain model class Table2.
 * @see Table2
 */
@RestController("WMSTUDIO.Table2Controller")
@RequestMapping("/WMSTUDIO/Table2")
@Api(description = "Exposes APIs to work with Table2 resource.", value = "Table2Controller")
public class Table2Controller {

    private static final Logger LOGGER = LoggerFactory.getLogger(Table2Controller.class);

    @Autowired
    @Qualifier("WMSTUDIO.Table2Service")
    private Table2Service table2Service;

    /**
     * @deprecated Use {@link #findTable2s(String)} instead.
     */
    @Deprecated
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @ApiOperation(value = "Returns the list of Table2 instances matching the search criteria.")
    public Page<Table2> findTable2s(Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Table2s list");
        return table2Service.findAll(queryFilters, pageable);
    }

    @RequestMapping(method = RequestMethod.GET)
    @ApiOperation(value = "Returns the list of Table2 instances matching the search criteria.")
    public Page<Table2> findTable2s(@RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Table2s list");
        return table2Service.findAll(query, pageable);
    }

    @RequestMapping(value = "/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @ApiOperation(value = "Returns downloadable file for the data.")
    public Downloadable exportTable2s(@PathVariable("exportType") ExportType exportType, @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        return table2Service.export(exportType, query, pageable);
    }

    @RequestMapping(value = "/{id:.+}/table2sForMergeFirmId", method = RequestMethod.GET)
    @ApiOperation(value = "Gets the table2sForMergeFirmId instance associated with the given id.")
    public Page<Table2> findAssociatedTable2sForMergeFirmId(Pageable pageable, @PathVariable("id") Long id) {
        LOGGER.debug("Fetching all associated table2sForMergeFirmId");
        return table2Service.findAssociatedValues(id, "table2ByMergeFirmId", "id", pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service Table2Service instance
	 */
    protected void setTable2Service(Table2Service service) {
        this.table2Service = service;
    }

    @RequestMapping(method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Creates a new Table2 instance.")
    public Table2 createTable2(@RequestBody Table2 table2) {
        LOGGER.debug("Create Table2 with information: {}", table2);
        table2 = table2Service.create(table2);
        LOGGER.debug("Created Table2 with information: {}", table2);
        return table2;
    }

    @RequestMapping(value = "/count", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the total count of Table2 instances.")
    public Long countTable2s(@RequestParam(value = "q", required = false) String query) {
        LOGGER.debug("counting Table2s");
        return table2Service.count(query);
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Returns the Table2 instance associated with the given id.")
    public Table2 getTable2(@PathVariable(value = "id") Long id) throws EntityNotFoundException {
        LOGGER.debug("Getting Table2 with id: {}", id);
        Table2 foundTable2 = table2Service.getById(id);
        LOGGER.debug("Table2 details with id: {}", foundTable2);
        return foundTable2;
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Updates the Table2 instance associated with the given id.")
    public Table2 editTable2(@PathVariable(value = "id") Long id, @RequestBody Table2 table2) throws EntityNotFoundException {
        LOGGER.debug("Editing Table2 with id: {}", table2.getId());
        table2.setId(id);
        table2 = table2Service.update(table2);
        LOGGER.debug("Table2 details with id: {}", table2);
        return table2;
    }

    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Deletes the Table2 instance associated with the given id.")
    public boolean deleteTable2(@PathVariable(value = "id") Long id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Table2 with id: {}", id);
        Table2 deletedTable2 = table2Service.delete(id);
        return deletedTable2 != null;
    }
}
