/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Composite1 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Composite1`", schema = "SARASWATHI")
@IdClass(Composite1Id.class)
public class Composite1 implements Serializable {

    private String stringCol;
    private int id;
    private short shortCol;
    private Table65 table65;

    @Id
    @Column(name = "`StringCol`", nullable = false, length = 255)
    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    @Id
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Id
    @Column(name = "`ShortCol`", nullable = false, scale = 0, precision = 5)
    public short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(short shortCol) {
        this.shortCol = shortCol;
    }


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns({
            @JoinColumn(name = "`COLUMN4`", referencedColumnName = "`StringCol`", insertable = false, updatable = false),
                    @JoinColumn(name = "`ID`", referencedColumnName = "`ID`", insertable = false, updatable = false),
                    @JoinColumn(name = "`ShortCol`", referencedColumnName = "`ShortCol`", insertable = false, updatable = false)})
    public Table65 getTable65() {
        return this.table65;
    }

    public void setTable65(Table65 table65) {
        this.id = table65.getId();
        this.shortCol = table65.getShortCol();

        this.table65 = table65;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Composite1)) return false;
        final Composite1 composite1 = (Composite1) o;
        return Objects.equals(getStringCol(), composite1.getStringCol()) &&
                Objects.equals(getId(), composite1.getId()) &&
                Objects.equals(getShortCol(), composite1.getShortCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStringCol(),
                getId(),
                getShortCol());
    }
}

