/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.wmstudio;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * Table112 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE112`", schema = "SARASWATHI")
@IdClass(Table112Id.class)
public class Table112 implements Serializable {

    private Long column1;
    private Long column2;

    @Id
    @Column(name = "`COLUMN1`", nullable = true, scale = 0, precision = 12)
    public Long getColumn1() {
        return this.column1;
    }

    public void setColumn1(Long column1) {
        this.column1 = column1;
    }

    @Id
    @Column(name = "`COLUMN2`", nullable = true, scale = 0, precision = 12)
    public Long getColumn2() {
        return this.column2;
    }

    public void setColumn2(Long column2) {
        this.column2 = column2;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table112)) return false;
        final Table112 table112 = (Table112) o;
        return Objects.equals(getColumn1(), table112.getColumn1()) &&
                Objects.equals(getColumn2(), table112.getColumn2());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getColumn1(),
                getColumn2());
    }
}

