/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/


package com.testing26thjuly_.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

public interface DB123TestingQueryExecutorService {
	int executeSV_InsertTypes(  java.lang.Integer id , java.lang.Byte bytecol , java.lang.Short shortcol , java.lang.Integer intcol , java.lang.Long longcol , java.math.BigInteger bigintcol , java.lang.Float floatcol , java.lang.Double doublecol , java.math.BigDecimal bigdeccol , java.lang.Character charcol , java.lang.String stringcol , java.lang.String textcol , java.lang.Boolean booleancol , org.joda.time.LocalDateTime datetimecol , java.sql.Timestamp timestampcol , java.sql.Date datecol , java.sql.Time timecol) throws QueryParameterMismatchException;

	
	Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) ;

	int executeWMCustomQueryUpdate(CustomQuery query) ;
}

