/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing26thjuly_.db123testing.Table21;

/**
 * Service object for domain model class Table21.
 *
 * @see {@link Table21}
 */
public interface Table21Service {

    /**
     * Creates a new Table21.
     *
     * @param table21 The information of the created CompositeTable.
     * @return The created Table21.
     */
	Table21 create(Table21 table21);


	/**
	 * Finds Table21 by id.
	 *
	 * @param table21Id The id of the wanted Table21.
	 * @return The found Table21. If no Table21 is found, this method returns null.
	 */
	Table21 getById(String table21Id) throws EntityNotFoundException;

	/**
	 * Updates the information of a Table21.
	 *
	 * @param table21 The information of the updated Table21.
	 * @return The updated Table21.
     *
	 * @throws EntityNotFoundException if no Table21 is found with given id.
	 */
	Table21 update(Table21 table21) throws EntityNotFoundException;

    /**
	 * Deletes a Table21.
	 *
	 * @param table21Id The id of the deleted Table21.
	 * @return The deleted Table21.
     *
	 * @throws EntityNotFoundException if no Table21 is found with the given id.
	 */
	Table21 delete(String table21Id) throws EntityNotFoundException;

	/**
	 * Finds all Table21s.
	 *
	 * @return A list of Table21s.
	 */
    @Deprecated
	Page<Table21> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all Table21s.
	 * @return A list of Table21s.
	 */
    Page<Table21> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table21s in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the Table21.
	 */
	long count(String query);

    Page<Table21> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

