/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing26thjuly_.db123testing.ViewSelfRelation;
import com.testing26thjuly_.db123testing.ViewSelfRelationId;

/**
 * ServiceImpl object for domain model class ViewSelfRelation.
 *
 * @see ViewSelfRelation
 */
@Service("DB123Testing.ViewSelfRelationService")
public class ViewSelfRelationServiceImpl implements ViewSelfRelationService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ViewSelfRelationServiceImpl.class);

    @Autowired
    @Qualifier("DB123Testing.ViewSelfRelationDao")
    private WMGenericDao<ViewSelfRelation, ViewSelfRelationId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<ViewSelfRelation, ViewSelfRelationId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

	@Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
	public ViewSelfRelation getById(ViewSelfRelationId viewselfrelationId) throws EntityNotFoundException {
        LOGGER.debug("Finding ViewSelfRelation by id: {}", viewselfrelationId);
        ViewSelfRelation viewselfrelation = this.wmGenericDao.findById(viewselfrelationId);
        if (viewselfrelation == null){
            LOGGER.debug("No ViewSelfRelation found with id: {}", viewselfrelationId);
            throw new EntityNotFoundException(String.valueOf(viewselfrelationId));
        }
        return viewselfrelation;
    }

	@Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
	public Page<ViewSelfRelation> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all ViewSelfRelations");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "DB123TestingTransactionManager")
    @Override
    public Page<ViewSelfRelation> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all ViewSelfRelations");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "DB123TestingTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service DB123Testing for table ViewSelfRelation to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "DB123TestingTransactionManager")
    @SuppressWarnings("unchecked")
	@Override
    public Page<ViewSelfRelation> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable) {
        LOGGER.debug("Fetching all associated");
        return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
    }
}

