/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing26thjuly_.db123testing.ViewTypesSpacing;
import com.testing26thjuly_.db123testing.ViewTypesSpacingId;

/**
 * Service object for domain model class ViewTypesSpacing.
 *
 * @see {@link ViewTypesSpacing}
 */
public interface ViewTypesSpacingService {


	/**
	 * Finds ViewTypesSpacing by id.
	 *
	 * @param viewTypesSpacingId The id of the wanted ViewTypesSpacing.
	 * @return The found ViewTypesSpacing. If no ViewTypesSpacing is found, this method returns null.
	 */
	ViewTypesSpacing getById(ViewTypesSpacingId viewTypesSpacingId) throws EntityNotFoundException;

	/**
	 * Finds all ViewTypesSpacings.
	 *
	 * @return A list of ViewTypesSpacings.
	 */
    @Deprecated
	Page<ViewTypesSpacing> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all ViewTypesSpacings.
	 * @return A list of ViewTypesSpacings.
	 */
    Page<ViewTypesSpacing> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the ViewTypesSpacings in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the ViewTypesSpacing.
	 */
	long count(String query);

    Page<ViewTypesSpacing> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

