/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing26thjuly_.db123testing.YesNoTable;

/**
 * Service object for domain model class YesNoTable.
 *
 * @see {@link YesNoTable}
 */
public interface YesNoTableService {

    /**
     * Creates a new YesNoTable.
     *
     * @param yesNoTable The information of the created CompositeTable.
     * @return The created YesNoTable.
     */
	YesNoTable create(YesNoTable yesNoTable);


	/**
	 * Finds YesNoTable by id.
	 *
	 * @param yesNoTableId The id of the wanted YesNoTable.
	 * @return The found YesNoTable. If no YesNoTable is found, this method returns null.
	 */
	YesNoTable getById(Integer yesNoTableId) throws EntityNotFoundException;

	/**
	 * Updates the information of a YesNoTable.
	 *
	 * @param yesNoTable The information of the updated YesNoTable.
	 * @return The updated YesNoTable.
     *
	 * @throws EntityNotFoundException if no YesNoTable is found with given id.
	 */
	YesNoTable update(YesNoTable yesNoTable) throws EntityNotFoundException;

    /**
	 * Deletes a YesNoTable.
	 *
	 * @param yesNoTableId The id of the deleted YesNoTable.
	 * @return The deleted YesNoTable.
     *
	 * @throws EntityNotFoundException if no YesNoTable is found with the given id.
	 */
	YesNoTable delete(Integer yesNoTableId) throws EntityNotFoundException;

	/**
	 * Finds all YesNoTables.
	 *
	 * @return A list of YesNoTables.
	 */
    @Deprecated
	Page<YesNoTable> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all YesNoTables.
	 * @return A list of YesNoTables.
	 */
    Page<YesNoTable> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the YesNoTables in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the YesNoTable.
	 */
	long count(String query);

    Page<YesNoTable> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

