/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.demo;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Table20 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE20`")
public class Table20 implements Serializable {

    private String id;
    private String column2;
    private List<Table9> table9s = new ArrayList<>();

    @Id
    @Column(name = "`ID`", nullable = false, length = 255)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "`COLUMN2`", nullable = true, length = 255)
    public String getColumn2() {
        return this.column2;
    }

    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "table20")
    public List<Table9> getTable9s() {
        return this.table9s;
    }

    public void setTable9s(List<Table9> table9s) {
        this.table9s = table9s;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table20)) return false;
        final Table20 table20 = (Table20) o;
        return Objects.equals(getId(), table20.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

