/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing26thjuly_.testingdb123;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Table6 generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE6`")
@IdClass(Table1Id.class)
public class Table6 implements Serializable {

    private int id;
    private String col3;
    private String column3;
    private String column4;
    private Table1 table1;

    @Id
    @Column(name = "`ID`", nullable = false, insertable = false, updatable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Id
    @Column(name = "`COL2`", nullable = false, insertable = false, updatable = false, length = 255)
    public String getCol3() {
        return this.col3;
    }

    public void setCol3(String col3) {
        this.col3 = col3;
    }

    @Column(name = "`COLUMN3`", nullable = false, length = 255)
    public String getColumn3() {
        return this.column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    @Column(name = "`COLUMN4`", nullable = true, length = 255)
    public String getColumn4() {
        return this.column4;
    }

    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    @PrimaryKeyJoinColumn
    @OneToOne(fetch = FetchType.EAGER)
    public Table1 getTable1() {
        return this.table1;
    }

    public void setTable1(Table1 table1) {
        this.id = table1.getId();
        this.col3 = table1.getCol3();

        this.table1 = table1;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table6)) return false;
        final Table6 table6 = (Table6) o;
        return Objects.equals(getId(), table6.getId()) &&
                Objects.equals(getCol3(), table6.getCol3());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getCol3());
    }
}

